registry {
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "zeus-nacos:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
}

config {
  type = "nacos"

  nacos {
    serverAddr = "zeus-nacos:8848"
    namespace = ""
    group = "SEATA_GROUP"
    dataId = "seata-server.yaml"
    username = "nacos"
    password = "nacos"
  }
}
