server:
  port: 8848

db:
  num: 1
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PWD:root}
  url:
    0: jdbc:mysql://${MYSQL_HOST:zeus-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:zeus_nacos}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

nacos:
  core:
    auth:
      system.type: nacos
      default.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql  #这个过期属性不能修改，nacos 代码对此有硬编码
  application:
    name: @project.artifactId@
  security:
    enabled: true


# 集群模式下监控数据接口
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  metrics:
#    export:
#      influx:
#        enabled: false
#      elastic:
#        enabled: false