server:
  port: 7300

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:zeus-nacos}:${NACOS_PORT:8848}
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        file-extension: yaml
#  config:
#    import:
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${file-extension}
  redis:
    host: zeus-redis
    port: 16379
    password: 1qaz@wsx?S
