server:
  port: 7200

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:zeus-nacos}:${NACOS_PORT:8848}
      config:
        enabled: false
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#  config:
#    import:
#      - optional:nacos:${spring.application.name}.yml
  elasticsearch:
    uris: http://zeus-es:9200


