### add
POST {{baseUrl}}/upms/tenant-type
Content-Type: application/json

{
  "name": "普通租户",
  "status": 0,
  "menuIds": [1, 2, 3]
}

### update
PUT {{baseUrl}}/upms/tenant-type
Content-Type: application/json

{
  "id": 4,
  "name": "普通租户",
  "status": 1,
  "menuIds": [1, 2, 3]
}

### delete
DELETE {{baseUrl}}/upms/tenant-type/2

### get
GET {{baseUrl}}/upms/tenant-type/1

### page
GET {{baseUrl}}/upms/tenant-type/page?size=5&current=1

### page
GET {{baseUrl}}/upms/tenant-type/list
