spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        - id: zeus-auth
          uri: lb://zeus-auth
          predicates:
            - Path=/auth/**
        - id: zeus-upms
          uri: lb://zeus-upms
          predicates:
            - Path=/admin/**
        - id: zeus-test-consumer
          uri: lb://zeus-test-consumer
          predicates:
            - Path=/consumer/**
        - id: zeus-test-producer
          uri: lb://zeus-test-producer
          predicates:
            - Path=/producer/**
          filters:
            - name: RequestRateLimiter
              args:
                deny-empty-key: true
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@remoteAddrKeyResolver}"