spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:zeus-kafka}:${KAFKA_PORT:9092}
    consumer:
      group-id: zeus-test-consumer #默认的消费组ID
      enable-auto-commit: false #是否自动提交offset
      auto-commit-interval: 2000 #提交offset延时
      auto-offset-reset: latest # 当kafka中没有初始offset或offset超出范围时将自动重置offset
      max-poll-records: 500 #单次拉取消息的最大条数
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session:
          timeout:
            ms: 120000 # 消费会话超时时间（超过这个时间 consumer 没有发送心跳，就会触发 rebalance 操作）
        request:
          timeout:
            ms: 18000 # 消费请求的超时时间
    listener:
      ack-mode: manual_immediate # 手动确认后自动提交
      type: batch
      missing-topics-fatal: false # 未发现topic时不报错；自动创建topic需要设置为 false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:zeus}
    password: ${MYSQL_PWD:NaCt9Enxkm0htIaj6wTNyp3w!W}
    url: jdbc:mysql://${MYSQL_HOST:ecs.alexchen.tech}:${MYSQL_PORT:3306}/${MYSQL_DB:zeus_test_consumer}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true