### add
POST {{baseUrl}}/upms/tenant
Content-Type: application/json

{
  "name": "admin",
  "status": 0,
  "tenantPlanId": 1,
  "tenantPlanName": "超级管理员"
}

### update
PUT {{baseUrl}}/upms/tenant
Content-Type: application/json

{
  "id": 1,
  "name": "admin",
  "status": 0,
  "tenantPlanId": 1,
  "tenantPlanName": "系统租户"
}

### delete
DELETE {{baseUrl}}/upms/tenant/1

### get
GET {{baseUrl}}/upms/tenant/1

### page
GET {{baseUrl}}/upms/tenant/page?size=5&current=1

### page
GET {{baseUrl}}/upms/tenant/list
