# 数据库配置
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeus?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8

# MyBatis Plus 的配置项
mybatis-plus:
  global-config:
    banner: false
