spring:
  redis:
    host: zeus-redis
    port: 16379
    password: 1qaz@wsx?S

# springdoc 配置，关闭 swagger-ui，仅提供接口，统一由网关提供界面
springdoc:
  api-docs:
    enabled: true
    path: /springdoc
  swagger-ui:
    enabled: false
