server:
  port: 8000



spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:zeus-nacos}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.${file-extension}
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${file-extension}
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://zeus-gateway:9000/oauth2/introspect
          client-id: zeus
          client-secret: zeus
