server:
  port: 8000

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:zeus-nacos}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:zeus-common.yml
      - optional:nacos:${spring.application.name}.yml
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://zeus-gateway:9000/oauth2/introspect
          client-id: zeus
          client-secret: zeus
