server:
  port: 8000

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${NACOS_HOST:zeus-nacos}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:application.yaml
#      - optional:nacos:${spring.application.name}.yaml
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://zeus-gateway:9000/oauth2/introspect
          client-id: zeus
          client-secret: zeus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: zeus
      password: 1qaz@wsx?S
      url: jdbc:mysql://47.106.253.235:3306/zeus_upms